apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-management
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.management.port }}
  selector:
    {{- include "netbird.selectorLabels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-management
