apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-signal
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-signal
spec:
  type: {{ .Values.signal.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
  selector:
    netbird-app: {{ include "netbird.fullname" . }}-signal
    {{- include "netbird.selectorLabels" . | nindent 4 }}
