name: Release Helm Chart

on:
  push:
    tags:
      - 'v*.*.*' # Adjust this pattern if needed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Configure git
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Set CHART_VERSION from Git Tag
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update chart version in Chart.yaml
        run: |
          sed -i "s/^version:.*/version: ${{ steps.vars.outputs.tag }}/" charts/*/Chart.yaml

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            helm dependency update "$chart" || true
            helm package "$chart" --destination packaged/
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: packaged
        env:
          CR_TOKEN: ${{ secrets.HELM_CHARTS_PAT }}
          CR_OWNER: cclloyd
          CR_REPO: helm-charts
          CR_PAGES_BRANCH: gh-pages

      # Optional: Trigger index update in target repo if needed