name: Publish Helm chart (via Chart Releaser)

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.HELM_CHARTS_PAT }}
        with:
          charts_dir: ./charts
          charts_repo_url: https://cclloyd.github.io/helm-charts

