name: Publish Helm chart helm-charts branch using gh-pages

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helm-netbird
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Prepare gh-pages branch and compute chart version
        id: prepare
        run: |
          set -e
          ref_type="${GITHUB_REF_TYPE:-}"
          ref_name="${GITHUB_REF_NAME:-}"

          # Find latest tag from source repo
          latest_tag=$(git ls-remote --tags origin \
            | awk '{print $2}' \
            | sed 's#refs/tags/##' \
            | sort -V \
            | tail -n1)

          if [ -z "$latest_tag" ]; then
            latest_tag="0.1.0"
          fi

          mkdir -p helm-charts
          GH_REPO_URL="https://github.com/cclloyd/helm-charts.git"
          if git ls-remote --exit-code --heads "$GH_REPO_URL" gh-pages > /dev/null; then
            git clone --single-branch --branch gh-pages "$GH_REPO_URL" helm-charts
            cd helm-charts
            # Figure out chart version logic based on branch/tag
            if [[ "${GITHUB_REF}" == refs/heads/dev ]]; then
              # On dev branch, append -N if necessary
              base_version_file="netbird-${latest_tag}.tgz"
              if [ ! -e "${base_version_file}" ]; then
                version="${latest_tag}"
              else
                max_ext=0
                for f in netbird-${latest_tag}-*.tgz; do
                  if [[ "$f" =~ netbird-${latest_tag}-([0-9]+)\.tgz ]]; then
                    num="${BASH_REMATCH[1]}"
                    if [[ $num -gt $max_ext ]]; then
                      max_ext=$num
                    fi
                  fi
                done
                next_ext=$((max_ext + 1))
                version="${latest_tag}-${next_ext}"
              fi
            elif [[ "${GITHUB_REF}" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              # On tag run, use the tag as version
              version="${ref_name}"
              # Remove 'v' prefix for Chart.yaml
              if [[ $version =~ ^v ]]; then
                version="${version:1}"
              fi
            else
              version="${latest_tag}"
            fi
            cd ..
          else
            # Initialize gh-pages branch if absent
            git clone --no-checkout "$GH_REPO_URL" helm-charts
            cd helm-charts
            git checkout --orphan gh-pages
            git rm -rf . || true
            git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            version="${latest_tag}"
            touch .nojekyll
            git add .nojekyll
            git commit -m "Initialize gh-pages with .nojekyll"
            cd ..
          fi
          # Remove 'v' prefix for Chart.yaml (if not already removed)
          version_for_chart="$version"
          if [[ "$version_for_chart" =~ ^v ]]; then
            version_for_chart="${version_for_chart:1}"
          fi
          echo "Using chart version: $version_for_chart"
          echo "VERSION=${version_for_chart}" >> $GITHUB_ENV
          echo "PKG_VERSION=$version" >> $GITHUB_ENV

      - name: Update Chart.yaml version
        run: |
          yq -i ".version = \"${VERSION}\"" Chart.yaml

      - name: Package NetBird chart
        run: |
          mkdir -p packages
          helm package ./ \
            --version "${VERSION}" \
            --destination packages

      - name: Copy packaged chart to subfolder (/charts/netbird)
        run: |
          mkdir -p helm-charts/charts/netbird
          cp packages/netbird-${PKG_VERSION}.tgz helm-charts/charts/netbird/

      - name: Regenerate index.yaml at root (recursive)
        run: |
          cd helm-charts
          CHARTS_URL='https://cclloyd.github.io/helm-charts/charts/netbird'
          INDEX_FILE="index.yaml"
          if [ -f "${INDEX_FILE}" ]; then
            helm repo index charts/netbird \
              --url "${CHARTS_URL}" \
              --merge "${INDEX_FILE}"
          else
            helm repo index charts/netbird \
              --url "${CHARTS_URL}"
          fi
          cp charts/netbird/index.yaml .

      - name: Commit & push to gh-pages
        run: |
          cd helm-charts
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add charts/netbird/netbird-*.tgz index.yaml .nojekyll
          git commit -m "[ci] Publish netbird chart ${PKG_VERSION}" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.HELM_CHARTS_PAT }}@github.com/cclloyd/helm-charts.git
          git push origin gh-pages